const data = ['hola', 2, 5, 'adios'];
var comparacion1 = data[1] > data[2];
console.log(comparacion1);
comparacion1 === true;
comparacion1 === false;
console.log("El segundo número es mayor");
console.log('Suma= ', data[1] + data[2]);
console.log('Resta= ', data[1] - data[2]);
console.log('Multiplicación= ', data[1] * data[2]);
console.log('División= ', data[1] / data[2]);
console.log('Cociente= ', data[1] % data[2]);
